<?php

namespace App\Controllers;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use App\Models\IklanModel;
use App\Models\LamaranModel;

class Iklan extends BaseController
{
	/**
	 * Class constructor.
	 */
	protected $Lamaran; //Default Models Of this Controler
	protected $Iklan;
	protected $pager;
	public function __construct()
	{
		$this->Iklan = new IklanModel(); //Set Default Models Of this Controler
		$this->Lamaran = new LamaranModel();
		$pager = \Config\Services::pager();
	}

	//INDEX
	public function index()
	{
		$id = session()->get('id');
		$iklan = $this->Iklan->where('id_perusahaan', $id)->orderBy('tanggal', 'desc')->paginate(5, 'paging');
		$lamaran = array();

		foreach ($iklan as $value) {
			$lamaranData = $this->Lamaran->where('id_iklan', $value['id'])->findAll();
			if ($lamaranData)
				foreach ($lamaranData as $lamaranValue) {
					array_push($lamaran, $lamaranValue);
				}
		}

		$data = [
			'content' => 'Iklan Kamu',
			'iklan' => $iklan,
			'lamaran' => $lamaran,
			'pager' => $this->Iklan->pager
		];
		return view('iklan/index_iklan', $data);
	}

	public function admin()
	{
		$data = [
			'content' => 'Pemasukan iklan',
			'iklan' => $this->Iklan->orderBy('tanggal', 'desc')->paginate(10, 'paging'),
			'pager' => $this->Iklan->pager
		];
		return view('iklan/admin_iklan', $data);
	}

	//READ
	public function read($id)
	{
		$data = [
			'content' => 'Read Pages',
			'data' => $this->Iklan->find($id), //find on data
			'lamaran' => $this->Lamaran->where('id_iklan', $id)->findAll()
		];
		return view('iklan/read_iklan', $data);
	}

	//CREATE
	public function create()
	{
		$data = [
			'content' => 'Iklan',
			'action' => site_url('Iklan/create_action'),
			'data' =>   [
				'id' => set_value('id'),
				'id_perusahaan' => set_value('id_perusahaan'),
				'nama_perusahaan' => set_value('nama_perusahaan'),
				'judul' => set_value('judul'),
				'deskripsi' => set_value('deskripsi'),
			]
		];
		return view('iklan/form_iklan', $data);
	}

	//ACTION CREATE
	public function create_action()
	{
		$data = [
			'id' => $this->request->getVar('id'),
			'id_perusahaan' => $this->request->getVar('id_perusahaan'),
			'nama_perusahaan' => $this->request->getVar('nama_perusahaan'),
			'judul' => $this->request->getVar('judul'),
			'tanggal' => $this->request->getVar('tanggal'),
			'deskripsi' => $this->request->getVar('deskripsi'),

		];
		$this->Iklan->save($data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/Iklan'));
	}

	//UPDATE
	public function update($id)
	{
		$dataFind = $this->Iklan->find($id);
		if ($dataFind == false) {
			return redirect()->to(base_url('/Iklan'));
		}
		$data = [
			'content' => 'Edit Iklan',
			'action' => 'iklan/update_action',
			'data' => $this->Iklan->find($id),
		];
		return view('iklan/form_iklan', $data);
	}

	public function update_action()
	{
		$id = $this->request->getVar('id');
		$row = $this->Iklan->find(['id' => $id]);

		$data = [
			'id' => $this->request->getVar('id'),
			'id_perusahaan' => $this->request->getVar('id_perusahaan'),
			'nama_perusahaan' => $this->request->getVar('nama_perusahaan'),
			'judul' => $this->request->getVar('judul'),
			'deskripsi' => $this->request->getVar('deskripsi'),
		];
		$this->Iklan->save($data);
		session()->setFlashdata('message', 'Update Record Success');

		return redirect()->to(base_url('iklan'));
	}

	//PEMBAYARAN
	public function pembayaran($id)
	{
		$dataFind = $this->Iklan->find($id);
		if ($dataFind == false) {
			return redirect()->to(base_url('/Iklan'));
		}
		$data = [
			'content' => 'Pembayaran',
			'action' => 'iklan/pembayaran_action',
			'data' => $this->Iklan->find($id),
		];
		return view('iklan/pembayaran_iklan', $data);
	}

	public function pembayaran_action()
	{
		$file = $this->request->getFile('buktiPembayaran');
		$file->move('bukti_pembayaran');

		$fileName = $file->getClientName();

		$data = [
			'id' => $this->request->getVar('id'),
			'id_perusahaan' => $this->request->getVar('id_perusahaan'),
			'nama_perusahaan' => $this->request->getVar('nama_perusahaan'),
			'judul' => $this->request->getVar('judul'),
			'tanggal' => $this->request->getVar('tanggal'),
			'deskripsi' => $this->request->getVar('deskripsi'),
			'status_pembayaran' => 'Terbayar',
			'bukti_pembayaran' => $fileName
		];
		$this->Iklan->save($data);
		session()->setFlashdata('message', 'Pembayaran Sukses');

		return redirect()->to(base_url('iklan'));
	}

	//DELETE
	public function delete($id)
	{
		$row = $this->Iklan->find(['id' => $id]);
		if ($row) {
			$this->Iklan->delete($id);
			session()->setFlashdata('message', 'Delete Record Success');
			return redirect()->to(base_url('/iklan'));
		} else {
			session()->setFlashdata('message', 'Record Not Found');
			return redirect()->to(base_url('/iklan'));
		}
	}
}

/* End of file Iklan.php */
 /* Location: ./app/controllers/Iklan.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2020-12-13 08:04:09 */