<?php

namespace App\Controllers;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use App\Models\IklanModel;
use App\Models\KandidatModel;
use App\Models\LamaranModel;

class Lamaran extends BaseController
{
	/**
	 * Class constructor.
	 */
	protected $Lamaran; //Default Models Of this Controler
	protected $Iklan;
	protected $Kandidat;
	protected $pager;
	public function __construct()
	{
		$this->Lamaran = new LamaranModel(); //Set Default Models Of this Controler
		$this->Iklan = new IklanModel();
		$this->Kandidat = new KandidatModel();
		$pager = \Config\Services::pager();
	}

	//INDEX
	public function index()
	{
		$id = session()->get('id');
		$data = [
			'content' => 'Lamaran Masuk',
			'data' => $this->Lamaran->paginate(5, 'paging'),
			'pager' => $this->Lamaran->pager
		];
		return view('lamaran/index_lamaran', $data);
	}

	//READ
	public function read($id)
	{
		$lamaran = $this->Lamaran->find($id);
		$kandidat = $this->Kandidat->find($lamaran['id_kandidat']);

		$data = [
			'content' => 'Read Pages',
			'lamaran' =>  $lamaran, //find on data
			'kandidat' => $kandidat
		];
		return view('lamaran/read_lamaran', $data);
	}

	//CREATE
	public function create($id)
	{
		$iklan = $this->Iklan->find($id);

		$data = [
			'action' => site_url('Lamaran/create_action'),
			'data' => $iklan //find on data
		];
		return view('lamaran/form_lamaran', $data);
	}

	//ACTION CREATE
	public function create_action()
	{
		if (!$this->validate([
			'nama' => [
				'rules' => 'required',
				'errors' => [
					'required' => '{field} harus diisi'
				]
			],
			'email' => [
				'rules' => 'required',
				'errors' => [
					'required' => '{field} harus diisi'
				]
			],
			'berkas' => [
				'rules' => 'uploaded[berkas]'
			],
		])) {
			session()->setFlashdata('error_form', $this->validator->listErrors());
			return redirect()->back()->withInput();
		}

		$file = $this->request->getFile('berkas');
		$file->move('file');

		$fileName = $file->getClientName();

		$data = [
			'id' => $this->request->getVar('id'),
			'id_kandidat' => $this->request->getVar('id_kandidat'),
			'id_iklan' => $this->request->getVar('id_iklan'),
			'nama' => $this->request->getVar('nama'),
			'email' => $this->request->getVar('email'),
			'berkas' => $fileName,
		];

		print_r($data);

		$this->Lamaran->save($data);
		session()->setFlashdata('message', 'Lamaran telah dimasukan');
		return redirect()->back();
	}
}

/* End of file Lamaran.php */
 /* Location: ./app/controllers/Lamaran.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2020-12-08 23:03:19 */