<?php namespace App\Models;
/**
* THIS CONTROLER CODEIGNITER 4
* Codeigniter Version 4.x
* Generated by LigatCode
**/
use CodeIgniter\Model;

class IklanModel extends Model
{
    protected $table      = 'iklan';
    protected $primaryKey = 'id';
    //To help protect against Mass Assignment Attacks, the Model class requires
    //that you list all of the field names that can be changed during inserts and updates
    // https://codeigniter4.github.io/userguide/models/model.html#protecting-fields
    protected $allowedFields = ['id','id_perusahaan','nama_perusahaan','judul','tanggal','deskripsi', 'status_pembayaran', 'bukti_pembayaran'];
}

/* End of file IklanModel.php */
/* Location: ./app/models/IklanModel.php */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2020-12-13 08:04:09 */