<?php namespace App\Models;
/**
* THIS CONTROLER CODEIGNITER 4
* Codeigniter Version 4.x
* Generated by LigatCode
**/
use CodeIgniter\Model;

class KandidatModel extends Model
{
    protected $table      = 'kandidat';
    protected $primaryKey = 'id';
    //To help protect against Mass Assignment Attacks, the Model class requires
    //that you list all of the field names that can be changed during inserts and updates
    // https://codeigniter4.github.io/userguide/models/model.html#protecting-fields
    protected $allowedFields = ['id','nama','email','alamat','deskripsi'];

}

/* End of file KandidatModel.php */
/* Location: ./app/models/KandidatModel.php */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2020-12-09 01:26:54 */