<?php

namespace App\Models;

/**
 * THIS CONTROLER CODEIGNITER 4
 * Codeigniter Version 4.x
 * Generated by LigatCode
 **/

use CodeIgniter\Model;

class UserModel extends Model
{
    protected $table      = 'user';
    protected $primaryKey = 'id';
    //To help protect against Mass Assignment Attacks, the Model class requires
    //that you list all of the field names that can be changed during inserts and updates
    // https://codeigniter4.github.io/userguide/models/model.html#protecting-fields
    protected $allowedFields = ['id', 'email', 'password', 'role'];

    public function validateLogin($email, $password)
    {

        $builder = $this->db->table($this->table);
        $builder->where('email', $email)->limit(1);
        $data = $builder->get();
        $result = $data->getRow();

        if ($result != null && password_verify($password, $result->password)) {
            $data = [
                'id'    => $result->id,
                'email'    => $result->email,
                'role'    => $result->role,
            ];
            return $data;
        }

        return array();
    }
}

/* End of file UserModel.php */
/* Location: ./app/models/UserModel.php */
/* Please DO NOT modify this information : */
/* Generated by Ligatcode Codeigniter 4 CRUD Generator 2020-12-09 00:29:11 */